import { useState, useRef } from "react";
import { useUsageLimit } from "../../hooks/useUsageLimit";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SEO from "../../components/SEO";
import { exportReport } from "../../utils/exportPDF";

const T = { bg: "#030712", card: "rgba(17,24,39,0.8)", accent: "#6366f1", cyan: "#14e3c5", green: "#22c55e", red: "#ef4444", yellow: "#fbbf24", white: "#f1f5f9", muted: "#94a3b8", border: "rgba(148,163,184,0.08)" };

async function computeHash(file) {
  const buffer = await file.arrayBuffer();
  const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
  return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("");
}

export default function FileHashScanner() {
  const { checkLimit, limitError } = useUsageLimit("file-hash");
  const [mode, setMode] = useState("file");
  const [hash, setHash] = useState("");
  const [fileName, setFileName] = useState("");
  const [fileSize, setFileSize] = useState(0);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [dragging, setDragging] = useState(false);
  const fileRef = useRef(null);

  const handleFile = async (file) => {
    if (!file) return;
    setFileName(file.name); setFileSize(file.size); setError("");
    const h = await computeHash(file);
    setHash(h);
  };

  const checkHash = async () => {
    if (!hash.trim()) return;
    const ok = await checkLimit();
    if (!ok) return;
    setLoading(true); setError(""); setResult(null);
    try {
      const res = await fetch("/api/tools?tool=file-hash-check", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hash: hash.trim() }) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setResult(data);
    } catch (e) { setError(e.message); }
    setLoading(false);
  };

  const doExport = () => {
    if (!result) return;
    exportReport({
      title: "File Hash Scan Report", subtitle: `Status: ${result.status.toUpperCase()}`,
      sections: [
        { heading: "Hash", items: [result.hash] },
        { heading: "Result", items: [`Status: ${result.status}`, result.fileName ? `File: ${result.fileName}` : "", result.signature ? `Signature: ${result.signature}` : "", result.message || ""].filter(Boolean) },
      ],
      footer: "Generated by SECUVION",
    });
  };

  const fmtSize = (b) => b > 1048576 ? `${(b / 1048576).toFixed(1)} MB` : b > 1024 ? `${(b / 1024).toFixed(1)} KB` : `${b} B`;

  return (
    <div style={{ minHeight: "100vh", background: T.bg, fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
      <SEO title="File Hash Scanner" description="Check if a file is malicious by scanning its hash against malware databases." path="/file-hash-scanner" />
      <Navbar />
      <div style={{ maxWidth: 700, margin: "0 auto", padding: "120px 20px 60px" }}>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: T.white, marginBottom: 8, fontFamily: "'Space Grotesk',sans-serif" }}>File Hash Scanner</h1>
        <p style={{ color: T.muted, fontSize: 14, marginBottom: 28 }}>Upload a file or paste a hash to check against malware databases. Your file never leaves your browser.</p>

        {/* Mode toggle */}
        <div style={{ display: "flex", gap: 8, marginBottom: 24 }}>
          {["file", "hash"].map(m => (
            <button key={m} onClick={() => { setMode(m); setResult(null); setError(""); }} style={{ padding: "10px 24px", borderRadius: 8, fontSize: 14, fontWeight: 600, cursor: "pointer", background: mode === m ? `linear-gradient(135deg,${T.accent},${T.cyan})` : "transparent", border: mode === m ? "none" : `1px solid ${T.border}`, color: mode === m ? "#fff" : T.muted, fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
              {m === "file" ? "Upload File" : "Paste Hash"}
            </button>
          ))}
        </div>

        {mode === "file" && (
          <div
            onDragOver={e => { e.preventDefault(); setDragging(true); }}
            onDragLeave={() => setDragging(false)}
            onDrop={e => { e.preventDefault(); setDragging(false); handleFile(e.dataTransfer.files[0]); }}
            onClick={() => fileRef.current?.click()}
            style={{ padding: "48px 24px", border: `2px dashed ${dragging ? T.accent : T.border}`, borderRadius: 16, textAlign: "center", cursor: "pointer", background: dragging ? "rgba(99,102,241,0.05)" : "transparent", transition: "all 0.2s", marginBottom: 20 }}
          >
            <input ref={fileRef} type="file" style={{ display: "none" }} onChange={e => handleFile(e.target.files[0])} />
            <div style={{ fontSize: 36, marginBottom: 8 }}>&#x1F4C1;</div>
            <p style={{ color: T.white, fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{fileName || "Drop a file or click to browse"}</p>
            {fileName && <p style={{ color: T.muted, fontSize: 13 }}>{fmtSize(fileSize)}</p>}
            {!fileName && <p style={{ color: T.muted, fontSize: 13 }}>File is hashed locally — never uploaded</p>}
          </div>
        )}

        {mode === "hash" && (
          <input value={hash} onChange={e => setHash(e.target.value)} placeholder="Paste MD5, SHA-1, or SHA-256 hash" style={{ width: "100%", padding: "14px 16px", background: "rgba(15,23,42,0.6)", border: `1px solid ${T.border}`, borderRadius: 10, color: T.white, fontSize: 14, outline: "none", boxSizing: "border-box", fontFamily: "'JetBrains Mono',monospace", marginBottom: 20, letterSpacing: 0.5 }} />
        )}

        {hash && (
          <div style={{ padding: "10px 14px", background: "rgba(15,23,42,0.5)", borderRadius: 8, border: `1px solid ${T.border}`, marginBottom: 20, wordBreak: "break-all" }}>
            <span style={{ fontSize: 11, color: T.muted }}>SHA-256: </span>
            <span style={{ fontSize: 12, color: T.cyan, fontFamily: "'JetBrains Mono',monospace" }}>{hash}</span>
          </div>
        )}

        <button onClick={checkHash} disabled={!hash || loading} style={{ width: "100%", padding: "16px", borderRadius: 10, border: "none", background: !hash ? "rgba(99,102,241,0.3)" : `linear-gradient(135deg,${T.accent},${T.cyan})`, color: "#fff", fontSize: 16, fontWeight: 700, cursor: !hash || loading ? "not-allowed" : "pointer", fontFamily: "'Space Grotesk',sans-serif", marginBottom: 24 }}>
          {loading ? "Scanning..." : "Check Hash"}
        </button>

        {(limitError || error) && <div style={{ padding: "12px 16px", background: "rgba(239,68,68,0.1)", borderRadius: 8, border: "1px solid rgba(239,68,68,0.2)", marginBottom: 20 }}><span style={{ fontSize: 13, color: T.red }}>{limitError || error}</span>{limitError && <a href="/pricing" style={{ fontSize: 13, color: T.accent, marginLeft: 8 }}>Upgrade</a>}</div>}

        {result && (
          <div style={{ background: T.card, border: `1px solid ${result.status === "clean" ? "rgba(34,197,94,0.2)" : result.status === "malicious" ? "rgba(239,68,68,0.2)" : "rgba(251,191,36,0.2)"}`, borderRadius: 16, padding: 28 }}>
            <div style={{ textAlign: "center", marginBottom: 20 }}>
              <div style={{ fontSize: 48, marginBottom: 8 }}>{result.status === "clean" ? "\u2705" : result.status === "malicious" ? "\u26D4" : "\u2753"}</div>
              <h3 style={{ fontSize: 22, fontWeight: 700, color: result.status === "clean" ? T.green : result.status === "malicious" ? T.red : T.yellow, fontFamily: "'Space Grotesk',sans-serif" }}>
                {result.status === "clean" ? "No Threats Found" : result.status === "malicious" ? "Malware Detected!" : "Unknown"}
              </h3>
              <p style={{ fontSize: 13, color: T.muted }}>{result.message || (result.signature ? `Signature: ${result.signature}` : "")}</p>
            </div>

            {result.status === "malicious" && (
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 16 }}>
                {[
                  { label: "File Name", value: result.fileName },
                  { label: "File Type", value: result.fileType },
                  { label: "Signature", value: result.signature },
                  { label: "First Seen", value: result.firstSeen ? new Date(result.firstSeen).toLocaleDateString() : "N/A" },
                ].map(i => (
                  <div key={i.label} style={{ padding: "10px 14px", background: "rgba(15,23,42,0.5)", borderRadius: 8, border: `1px solid ${T.border}` }}>
                    <div style={{ fontSize: 11, color: T.muted, marginBottom: 2 }}>{i.label}</div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: T.white }}>{i.value || "N/A"}</div>
                  </div>
                ))}
              </div>
            )}

            {result.tags && result.tags.length > 0 && (
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 16 }}>
                {result.tags.map(t => <span key={t} style={{ padding: "4px 10px", borderRadius: 4, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)", fontSize: 12, color: T.red }}>{t}</span>)}
              </div>
            )}

            <button onClick={doExport} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${T.border}`, background: "rgba(15,23,42,0.6)", color: T.muted, fontSize: 12, cursor: "pointer" }}>Export Report</button>
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
}
