import { useState } from "react";
import { useUsageLimit } from "../../hooks/useUsageLimit";
import { LuSparkles, LuCheck, LuCircleCheck, LuCircleX, LuTriangleAlert } from "react-icons/lu";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SEO from "../../components/SEO";
import { exportReport } from "../../utils/exportPDF";

const T = { bg: "#060a14", card: "rgba(17,24,39,0.8)", accent: "#6366f1", cyan: "#14b8a6", green: "#22c55e", red: "#ef4444", yellow: "#fbbf24", white: "#f1f5f9", muted: "#94a3b8", border: "rgba(148,163,184,0.08)" };

const gradeColor = { A: "#22c55e", B: "#14b8a6", C: "#fbbf24", D: "#f97316", E: "#ef4444", F: "#ef4444" };
const StatusIcon = ({ status }) => {
  if (status === "present") return <LuCircleCheck size={16} color="#22c55e" />;
  if (status === "missing") return <LuCircleX size={16} color="#ef4444" />;
  return <LuTriangleAlert size={16} color="#fbbf24" />;
};

export default function SecurityHeaders() {
  const { checkLimit, limitError } = useUsageLimit("security-headers");
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  // AI auto-fix state — copy-paste-ready replacement headers from Gemini.
  const [fixLoading, setFixLoading] = useState(false);
  const [fix, setFix] = useState(null);
  const [fixError, setFixError] = useState("");
  const [copied, setCopied] = useState(false);

  const generateFix = async () => {
    if (!result) return;
    setFixLoading(true); setFixError(""); setFix(null);
    try {
      // Reduce payload — pass only header names + status, plus full values where set
      const headersMap = {};
      const missing = [];
      result.headers.forEach((h) => {
        if (h.status === "present" || h.status === "misconfigured") headersMap[h.name] = h.value || "";
        if (h.status === "missing" || h.status === "misconfigured") missing.push(h.name);
      });
      const r = await fetch("/api/tools?tool=headers-fix", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: result.url, headers: headersMap, missing }),
      });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error || "Fix generation failed");
      setFix(data);
    } catch (e) { setFixError(e.message); }
    finally { setFixLoading(false); }
  };

  const copyFix = () => {
    if (!fix?.fixedHeaders) return;
    navigator.clipboard.writeText(fix.fixedHeaders);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const scan = async () => {
    if (!url.trim()) return;
    const ok = await checkLimit();
    if (!ok) return;
    setLoading(true); setError(""); setResult(null);
    try {
      const res = await fetch("/api/tools?tool=security-headers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: url.trim() }) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setResult(data);
    } catch (e) { setError(e.message); }
    setLoading(false);
  };

  const doExport = () => {
    if (!result) return;
    exportReport({
      title: "Security Headers Report", subtitle: `${result.url} — Grade: ${result.grade} (${result.score}/100)`,
      sections: [
        { heading: "Summary", items: [`Grade: ${result.grade}`, `Score: ${result.score}/100`, `Present: ${result.summary.present}`, `Missing: ${result.summary.missing}`, `Misconfigured: ${result.summary.misconfigured}`] },
        ...result.headers.map(h => ({ heading: h.name, items: [`Status: ${h.status}`, `Value: ${h.value || "Not set"}`, h.description, h.note ? `Note: ${h.note}` : ""].filter(Boolean) })),
      ],
      footer: "Generated by VRIKAAN",
    });
  };

  return (
    <div style={{ minHeight: "100vh", background: T.bg, fontFamily: "'Vrikaan Sans',sans-serif" }}>
      <SEO title="Security Headers Checker" description="Analyze any website's HTTP security headers and get a security grade." path="/security-headers" />
      <Navbar />
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "120px 20px 60px" }}>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: T.white, marginBottom: 8, fontFamily: "'Vrikaan Sans',sans-serif" }}>Security Headers Checker</h1>
        <p style={{ color: T.muted, fontSize: 14, marginBottom: 28 }}>Analyze any website's HTTP security headers and get a security grade.</p>

        <div style={{ display: "flex", gap: 10, marginBottom: 28 }}>
          <input value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === "Enter" && scan()} placeholder="https://example.com" style={{ flex: 1, padding: "14px 16px", background: "rgba(15,23,42,0.6)", border: `1px solid ${T.border}`, borderRadius: 10, color: T.white, fontSize: 15, outline: "none", boxSizing: "border-box", fontFamily: "'Vrikaan Sans',sans-serif" }} />
          <button onClick={scan} disabled={loading} style={{ padding: "14px 28px", borderRadius: 10, border: "none", background: `linear-gradient(135deg,${T.accent},${T.cyan})`, color: "#fff", fontSize: 15, fontWeight: 700, cursor: loading ? "wait" : "pointer", fontFamily: "'Vrikaan Sans',sans-serif", whiteSpace: "nowrap" }}>
            {loading ? "Scanning..." : "Scan Headers"}
          </button>
        </div>

        {(limitError || error) && <div style={{ padding: "12px 16px", background: "rgba(239,68,68,0.1)", borderRadius: 8, border: "1px solid rgba(239,68,68,0.2)", marginBottom: 20 }}><span style={{ fontSize: 13, color: T.red }}>{limitError || error}</span>{limitError && <a href="/pricing" style={{ fontSize: 13, color: T.accent, marginLeft: 8 }}>Upgrade</a>}</div>}

        {result && (
          <div style={{ background: T.card, border: `1px solid ${T.border}`, borderRadius: 16, padding: 28, backdropFilter: "blur(10px)" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }}>
              {/* Grade circle */}
              <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
                <div style={{ width: 80, height: 80, borderRadius: "50%", border: `3px solid ${gradeColor[result.grade]}`, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column" }}>
                  <span style={{ fontSize: 32, fontWeight: 800, color: gradeColor[result.grade], fontFamily: "'Vrikaan Sans',sans-serif", lineHeight: 1 }}>{result.grade}</span>
                </div>
                <div>
                  <div style={{ fontSize: 24, fontWeight: 700, color: T.white, fontFamily: "'Vrikaan Sans',sans-serif" }}>{result.score}/100</div>
                  <div style={{ fontSize: 13, color: T.muted }}>{result.summary.present} present, {result.summary.missing} missing</div>
                </div>
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                <button onClick={generateFix} disabled={fixLoading || result.summary.missing + result.summary.misconfigured === 0} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${T.cyan}40`, background: "rgba(20, 184, 166,0.15)", color: T.cyan, fontSize: 12, fontWeight: 600, cursor: fixLoading ? "wait" : "pointer", opacity: result.summary.missing + result.summary.misconfigured === 0 ? 0.5 : 1 }}>
                  {fixLoading ? "Generating…" : <><LuSparkles size={13} style={{ verticalAlign: "-2px" }} /> AI Auto-Fix</>}
                </button>
                <button onClick={doExport} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${T.border}`, background: "rgba(15,23,42,0.6)", color: T.muted, fontSize: 12, cursor: "pointer" }}>Export PDF</button>
              </div>
            </div>

            {/* AI auto-fix result */}
            {fixError && <div style={{ padding: 12, marginBottom: 16, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)", borderRadius: 8, color: T.red, fontSize: 13 }}>{fixError}</div>}
            {fix && (
              <div style={{ marginBottom: 24, padding: 18, background: "rgba(20, 184, 166,0.06)", border: `1px solid ${T.cyan}30`, borderRadius: 12 }}>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12, paddingBottom: 12, borderBottom: `1px solid ${T.border}` }}>
                  <div>
                    <span style={{ color: T.cyan, fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}><LuSparkles size={13} style={{ verticalAlign: "-2px" }} /> AI Auto-Fix</span>
                    <p style={{ margin: "2px 0 0", color: T.muted, fontSize: 11 }}>Copy-paste-ready replacement headers</p>
                  </div>
                  <button onClick={copyFix} style={{ padding: "8px 14px", borderRadius: 8, border: "none", background: copied ? T.green : `linear-gradient(135deg, ${T.accent}, ${T.cyan})`, color: "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer" }}>{copied ? <><LuCheck size={13} style={{ verticalAlign: "-2px" }} /> Copied</> : "Copy headers"}</button>
                </div>
                <pre style={{ margin: 0, padding: 14, background: "rgba(3,7,18,0.6)", border: `1px solid ${T.border}`, borderRadius: 8, fontFamily: "'Vrikaan Mono', monospace", fontSize: 12, color: T.white, overflowX: "auto", lineHeight: 1.6, whiteSpace: "pre-wrap" }}>{fix.fixedHeaders}</pre>
                {fix.explanations?.length > 0 && (
                  <details style={{ marginTop: 14 }}>
                    <summary style={{ color: T.cyan, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>Why these values?</summary>
                    <ul style={{ margin: "8px 0 0", paddingLeft: 20, color: T.muted, fontSize: 12, lineHeight: 1.7 }}>
                      {fix.explanations.map((e, i) => (
                        <li key={i}><strong style={{ color: T.white }}>{e.header}</strong>: {e.why}</li>
                      ))}
                    </ul>
                  </details>
                )}
                {fix.platformTips && (Object.keys(fix.platformTips).length > 0) && (
                  <details style={{ marginTop: 8 }}>
                    <summary style={{ color: T.cyan, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>How to deploy on your server</summary>
                    <div style={{ marginTop: 8, color: T.muted, fontSize: 12, lineHeight: 1.7 }}>
                      {Object.entries(fix.platformTips).map(([platform, tip]) => tip ? (
                        <div key={platform} style={{ marginBottom: 8 }}>
                          <strong style={{ color: T.white, textTransform: "capitalize" }}>{platform}:</strong> <span style={{ whiteSpace: "pre-wrap" }}>{tip}</span>
                        </div>
                      ) : null)}
                    </div>
                  </details>
                )}
              </div>
            )}

            {/* Headers list */}
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {result.headers.map(h => (
                <div key={h.name} style={{ padding: "14px 16px", background: "rgba(15,23,42,0.5)", borderRadius: 10, border: `1px solid ${h.status === "present" ? "rgba(34,197,94,0.15)" : h.status === "missing" ? "rgba(239,68,68,0.15)" : "rgba(251,191,36,0.15)"}` }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                    <StatusIcon status={h.status} />
                    <span style={{ fontSize: 14, fontWeight: 600, color: T.white }}>{h.name}</span>
                  </div>
                  <div style={{ fontSize: 12, color: T.muted, marginBottom: h.value || h.note ? 6 : 0 }}>{h.description}</div>
                  {h.value && <div style={{ fontSize: 12, fontFamily: "'Vrikaan Mono',monospace", color: T.cyan, padding: "6px 10px", background: "rgba(15,23,42,0.6)", borderRadius: 6, wordBreak: "break-all", marginBottom: h.note ? 4 : 0 }}>{h.value}</div>}
                  {!h.value && h.status === "missing" && <div style={{ fontSize: 12, color: T.red, fontStyle: "italic" }}>Not set</div>}
                  {h.note && <div style={{ fontSize: 11, color: T.yellow, marginTop: 2 }}>{h.note}</div>}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
}
