import { useState } from "react";
import { useUsageLimit } from "../../hooks/useUsageLimit";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SEO from "../../components/SEO";
import { exportReport } from "../../utils/exportPDF";

const T = { bg: "#030712", card: "rgba(17,24,39,0.8)", accent: "#6366f1", cyan: "#14e3c5", green: "#22c55e", red: "#ef4444", yellow: "#fbbf24", white: "#f1f5f9", muted: "#94a3b8", border: "rgba(148,163,184,0.08)" };

const gradeColor = { A: "#22c55e", B: "#14e3c5", C: "#fbbf24", D: "#f97316", E: "#ef4444", F: "#ef4444" };
const statusIcon = { present: "\u2705", missing: "\u274C", misconfigured: "\u26A0\uFE0F" };

export default function SecurityHeaders() {
  const { checkLimit, limitError } = useUsageLimit("security-headers");
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  const scan = async () => {
    if (!url.trim()) return;
    const ok = await checkLimit();
    if (!ok) return;
    setLoading(true); setError(""); setResult(null);
    try {
      const res = await fetch("/api/tools?tool=security-headers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: url.trim() }) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setResult(data);
    } catch (e) { setError(e.message); }
    setLoading(false);
  };

  const doExport = () => {
    if (!result) return;
    exportReport({
      title: "Security Headers Report", subtitle: `${result.url} — Grade: ${result.grade} (${result.score}/100)`,
      sections: [
        { heading: "Summary", items: [`Grade: ${result.grade}`, `Score: ${result.score}/100`, `Present: ${result.summary.present}`, `Missing: ${result.summary.missing}`, `Misconfigured: ${result.summary.misconfigured}`] },
        ...result.headers.map(h => ({ heading: h.name, items: [`Status: ${h.status}`, `Value: ${h.value || "Not set"}`, h.description, h.note ? `Note: ${h.note}` : ""].filter(Boolean) })),
      ],
      footer: "Generated by SECUVION",
    });
  };

  return (
    <div style={{ minHeight: "100vh", background: T.bg, fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
      <SEO title="Security Headers Checker" description="Analyze any website's HTTP security headers and get a security grade." path="/security-headers" />
      <Navbar />
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "120px 20px 60px" }}>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: T.white, marginBottom: 8, fontFamily: "'Space Grotesk',sans-serif" }}>Security Headers Checker</h1>
        <p style={{ color: T.muted, fontSize: 14, marginBottom: 28 }}>Analyze any website's HTTP security headers and get a security grade.</p>

        <div style={{ display: "flex", gap: 10, marginBottom: 28 }}>
          <input value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === "Enter" && scan()} placeholder="https://example.com" style={{ flex: 1, padding: "14px 16px", background: "rgba(15,23,42,0.6)", border: `1px solid ${T.border}`, borderRadius: 10, color: T.white, fontSize: 15, outline: "none", boxSizing: "border-box", fontFamily: "'Plus Jakarta Sans',sans-serif" }} />
          <button onClick={scan} disabled={loading} style={{ padding: "14px 28px", borderRadius: 10, border: "none", background: `linear-gradient(135deg,${T.accent},${T.cyan})`, color: "#fff", fontSize: 15, fontWeight: 700, cursor: loading ? "wait" : "pointer", fontFamily: "'Space Grotesk',sans-serif", whiteSpace: "nowrap" }}>
            {loading ? "Scanning..." : "Scan Headers"}
          </button>
        </div>

        {(limitError || error) && <div style={{ padding: "12px 16px", background: "rgba(239,68,68,0.1)", borderRadius: 8, border: "1px solid rgba(239,68,68,0.2)", marginBottom: 20 }}><span style={{ fontSize: 13, color: T.red }}>{limitError || error}</span>{limitError && <a href="/pricing" style={{ fontSize: 13, color: T.accent, marginLeft: 8 }}>Upgrade</a>}</div>}

        {result && (
          <div style={{ background: T.card, border: `1px solid ${T.border}`, borderRadius: 16, padding: 28, backdropFilter: "blur(10px)" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }}>
              {/* Grade circle */}
              <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
                <div style={{ width: 80, height: 80, borderRadius: "50%", border: `3px solid ${gradeColor[result.grade]}`, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column" }}>
                  <span style={{ fontSize: 32, fontWeight: 800, color: gradeColor[result.grade], fontFamily: "'Space Grotesk',sans-serif", lineHeight: 1 }}>{result.grade}</span>
                </div>
                <div>
                  <div style={{ fontSize: 24, fontWeight: 700, color: T.white, fontFamily: "'Space Grotesk',sans-serif" }}>{result.score}/100</div>
                  <div style={{ fontSize: 13, color: T.muted }}>{result.summary.present} present, {result.summary.missing} missing</div>
                </div>
              </div>
              <button onClick={doExport} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${T.border}`, background: "rgba(15,23,42,0.6)", color: T.muted, fontSize: 12, cursor: "pointer" }}>Export PDF</button>
            </div>

            {/* Headers list */}
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {result.headers.map(h => (
                <div key={h.name} style={{ padding: "14px 16px", background: "rgba(15,23,42,0.5)", borderRadius: 10, border: `1px solid ${h.status === "present" ? "rgba(34,197,94,0.15)" : h.status === "missing" ? "rgba(239,68,68,0.15)" : "rgba(251,191,36,0.15)"}` }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                    <span style={{ fontSize: 14 }}>{statusIcon[h.status]}</span>
                    <span style={{ fontSize: 14, fontWeight: 600, color: T.white }}>{h.name}</span>
                  </div>
                  <div style={{ fontSize: 12, color: T.muted, marginBottom: h.value || h.note ? 6 : 0 }}>{h.description}</div>
                  {h.value && <div style={{ fontSize: 12, fontFamily: "'JetBrains Mono',monospace", color: T.cyan, padding: "6px 10px", background: "rgba(15,23,42,0.6)", borderRadius: 6, wordBreak: "break-all", marginBottom: h.note ? 4 : 0 }}>{h.value}</div>}
                  {!h.value && h.status === "missing" && <div style={{ fontSize: 12, color: T.red, fontStyle: "italic" }}>Not set</div>}
                  {h.note && <div style={{ fontSize: 11, color: T.yellow, marginTop: 2 }}>{h.note}</div>}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
}
