import { useState, useEffect, useMemo } from "react";
import ToolShell from "../../components/ToolShell";
import SeniorModeBanner from "../../components/SeniorModeBanner";
import { LuTriangleAlert, LuCircleCheck, LuLock } from "react-icons/lu";

const T = {
  bg: "#060a14", card: "rgba(17,24,39,0.7)",
  accent: "#6366f1", cyan: "#14b8a6",
  green: "#22c55e", red: "#ef4444", orange: "#f97316", yellow: "#fbbf24",
  white: "#f1f5f9", muted: "#94a3b8", mutedDark: "#64748b",
  border: "rgba(148,163,184,0.12)",
};

// Crowdsourced scam UPI list (localStorage). When you find a scam UPI ID,
// add it here — the entry helps anyone else who looks it up later. We'll
// sync this to a Firestore-backed shared list in v2.
const STORAGE_KEY = "vrk_scam_upi_db_v1";

const SEED = [
  // Pre-seeded with common scam pattern examples (these are FAKE / illustrative;
  // do not use them as legit reports — they exist so the page demos correctly).
  { vpa: "fakescamupi@paytm", reportedBy: "VRIKAAN seed", date: "2024-12-01", category: "Fake KYC", evidence: "Repeatedly used in WhatsApp KYC scams targeting SBI customers" },
  { vpa: "loantrap@upi", reportedBy: "VRIKAAN seed", date: "2024-11-20", category: "Loan harassment", evidence: "Loan-app harassment collector ID" },
  { vpa: "deliveryscam@oksbi", reportedBy: "VRIKAAN seed", date: "2024-10-15", category: "Fake delivery", evidence: "Reported in 14 Mumbai-area parcel-customs scams" },
];

// Valid UPI VPA format: handle@psp (PSP = paytm, oksbi, ybl, ibl, axl, hdfcbank, icici, upi, etc.)
const VPA_RX = /^[a-zA-Z0-9._-]+@[a-zA-Z][a-zA-Z0-9]*$/;

const RED_FLAG_HANDLES = [
  // Random / fly-by-night handles often used by scammers
  "trap", "scam", "loan", "instant", "quick", "easy", "free", "win", "lucky",
  "kyc", "verify", "update", "support", "help", "refund", "block", "claim",
];

const TRUSTED_PSPS = [
  "paytm", "ybl",       // PhonePe
  "oksbi", "okhdfc", "okicici", "okaxis", // Google Pay
  "ibl",                // ICICI
  "axl",                // Axis
  "hdfcbank", "icici", "sbi", "axis", "kotak",
  "upi", "okupi",
  "airtel", "freecharge", "amazonpay",
];

const CATEGORIES = ["Fake KYC", "Loan harassment", "Fake delivery", "Investment scam", "Job scam", "Romance scam", "Charity scam", "Other"];

function loadDB() {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
    return [...SEED, ...stored];
  } catch { return SEED; }
}
function saveUserReport(entry) {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
    stored.push(entry);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(stored));
  } catch {}
}

function analyzeVpa(vpa) {
  const findings = [];
  if (!VPA_RX.test(vpa)) {
    findings.push({ severity: "high", text: "Invalid VPA format. Real UPI IDs look like 'name@psp'." });
    return { findings, valid: false };
  }
  const [handle, psp] = vpa.toLowerCase().split("@");

  if (!TRUSTED_PSPS.includes(psp)) {
    findings.push({ severity: "medium", text: `PSP "${psp}" is not a major Indian provider. Could be a payment aggregator — verify carefully.` });
  }
  for (const flag of RED_FLAG_HANDLES) {
    if (handle.includes(flag)) {
      findings.push({ severity: "high", text: `Handle contains red-flag word "${flag}" — common in scam VPAs.` });
      break;
    }
  }
  if (/^\d+$/.test(handle)) {
    findings.push({ severity: "medium", text: "Handle is all numbers — usually phone-number-as-VPA, which is fine for individuals but unusual for businesses." });
  }
  if (handle.length < 4) {
    findings.push({ severity: "medium", text: "Handle is very short (≤4 chars) — common for throwaway scam VPAs." });
  }
  if (/^[a-z]+\d{4,}$/.test(handle)) {
    findings.push({ severity: "low", text: "Handle looks autogenerated (word + 4+ digits) — could be legitimate or a churn VPA." });
  }
  return { findings, valid: true, handle, psp };
}

export default function UpiHoneypot() {
  const [db, setDb] = useState(() => loadDB());
  const [query, setQuery] = useState("");
  const [reporting, setReporting] = useState(false);
  const [reportCategory, setReportCategory] = useState("Fake KYC");
  const [reportEvidence, setReportEvidence] = useState("");
  const [reportSuccess, setReportSuccess] = useState(false);

  const queryClean = query.trim().toLowerCase();
  const analysis = useMemo(() => queryClean ? analyzeVpa(queryClean) : null, [queryClean]);
  const matchInDb = useMemo(() => queryClean ? db.find(e => e.vpa.toLowerCase() === queryClean) : null, [db, queryClean]);

  const submitReport = () => {
    if (!queryClean || !VPA_RX.test(queryClean) || !reportEvidence.trim()) return;
    const entry = {
      vpa: queryClean,
      reportedBy: "You (local)",
      date: new Date().toISOString().slice(0, 10),
      category: reportCategory,
      evidence: reportEvidence.trim().slice(0, 300),
    };
    saveUserReport(entry);
    setDb(loadDB());
    setReportSuccess(true);
    setReporting(false);
    setReportEvidence("");
  };

  const riskScore = useMemo(() => {
    if (!analysis) return null;
    if (matchInDb) return 100;
    if (!analysis.valid) return 100;
    const score = analysis.findings.reduce((s, f) => s + (f.severity === "high" ? 40 : f.severity === "medium" ? 20 : 5), 0);
    return Math.min(100, score);
  }, [analysis, matchInDb]);

  const verdict = riskScore == null ? null
    : riskScore >= 70 ? { label: "DO NOT PAY", color: T.red }
    : riskScore >= 40 ? { label: "HIGH SUSPICION", color: T.orange }
    : riskScore >= 15 ? { label: "BE CAREFUL", color: T.yellow }
    : { label: "LOOKS NORMAL", color: T.green };

  return (
    <ToolShell
      route="/upi-lookup" eyebrow="UPI Safety"
      title="Check that UPI ID" titleAccent="before you pay."
      subtitle="Paste any UPI / VPA → instant red-flag analysis + community scam database lookup. Saves lakhs."
      width={900}
      seoTitle="UPI Scam Lookup — Check Before You Pay"
      seoDesc="Paste any UPI ID before sending money. We check format, red flags, and a crowdsourced scam database. Free, India-built."
      path="/upi-lookup"
      topSlot={<SeniorModeBanner />}
      footer
    >

      <main style={{ maxWidth: 900, margin: "0 auto", padding: "0" }}>

        {/* Lookup field */}
        <div style={{
          background: T.card, border: `1px solid ${T.border}`, borderRadius: 16, padding: 20,
          marginBottom: 18,
        }}>
          <input
            value={query}
            onChange={(e) => { setQuery(e.target.value); setReportSuccess(false); }}
            placeholder="e.g. sahilnikam@paytm or 9876543210@upi"
            style={{
              width: "100%", padding: "16px 18px", borderRadius: 12,
              background: "rgba(2,6,23,0.6)", border: `2px solid ${T.border}`,
              color: T.white, fontSize: 18, fontWeight: 600, outline: "none",
              fontFamily: "ui-monospace, Menlo, monospace", letterSpacing: 0.5,
              boxSizing: "border-box",
            }}
          />
        </div>

        {/* Verdict */}
        {verdict && (
          <div style={{
            padding: 22, borderRadius: 16, marginBottom: 18,
            background: `${verdict.color}1a`, border: `2px solid ${verdict.color}`,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap", marginBottom: 10 }}>
              <div>
                <div style={{
                  fontSize: 11, fontWeight: 800, letterSpacing: 2, color: verdict.color,
                  textTransform: "uppercase", marginBottom: 4,
                }}>Verdict</div>
                <div style={{
                  fontFamily: "'Vrikaan Sans', sans-serif", fontSize: 28, fontWeight: 800,
                  color: verdict.color, lineHeight: 1.1,
                }}>{verdict.label}</div>
                <div style={{ color: T.muted, fontSize: 13, marginTop: 4 }}>Risk score: {riskScore}/100</div>
              </div>
            </div>

            {matchInDb && (
              <div style={{
                padding: 14, borderRadius: 10,
                background: `${T.red}1a`, border: `1px solid ${T.red}55`,
                color: T.white, fontSize: 13, lineHeight: 1.7,
              }}>
                <LuTriangleAlert size={13} style={{ verticalAlign: "-2px" }} /> <strong>This UPI was REPORTED as scam.</strong><br/>
                Category: <strong style={{ color: T.red }}>{matchInDb.category}</strong> · Reported {matchInDb.date} by {matchInDb.reportedBy}<br/>
                Evidence: "{matchInDb.evidence}"
              </div>
            )}

            {analysis?.findings.length > 0 && (
              <div style={{ marginTop: 12, display: "grid", gap: 8 }}>
                {analysis.findings.map((f, i) => {
                  const c = f.severity === "high" ? T.red : f.severity === "medium" ? T.orange : T.yellow;
                  return (
                    <div key={i} style={{
                      padding: "10px 14px", borderRadius: 8,
                      background: `${c}0a`, border: `1px solid ${c}33`,
                      color: T.muted, fontSize: 13, lineHeight: 1.5,
                    }}>
                      <span style={{
                        display: "inline-block",
                        fontSize: 9, fontWeight: 800, letterSpacing: 1,
                        padding: "2px 6px", borderRadius: 4,
                        background: c, color: T.bg,
                        marginRight: 8, textTransform: "uppercase",
                      }}>{f.severity}</span>
                      {f.text}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}

        {/* Report this VPA as scam */}
        {analysis?.valid && !matchInDb && (
          <div style={{
            background: T.card, border: `1px solid ${T.border}`, borderRadius: 14,
            padding: 20, marginBottom: 18,
          }}>
            {reportSuccess ? (
              <div style={{ color: T.green, fontWeight: 700, textAlign: "center", padding: 10 }}>
                <LuCircleCheck size={14} style={{ verticalAlign: "-2px" }} /> Reported. Saved to your local database. Thanks for helping protect others.
              </div>
            ) : !reporting ? (
              <div style={{ textAlign: "center" }}>
                <p style={{ color: T.muted, fontSize: 13, margin: "0 0 12px" }}>
                  Did this UPI ID scam you? Report it — others looking up this ID will see your warning.
                </p>
                <button onClick={() => setReporting(true)} style={{
                  padding: "10px 20px", borderRadius: 10,
                  background: T.red, color: "#fff", border: 0,
                  fontWeight: 700, fontSize: 13, cursor: "pointer", fontFamily: "inherit",
                }}><LuTriangleAlert size={13} style={{ verticalAlign: "-2px" }} /> Report this UPI as scam</button>
              </div>
            ) : (
              <div style={{ display: "grid", gap: 10 }}>
                <select
                  value={reportCategory} onChange={(e) => setReportCategory(e.target.value)}
                  style={inputStyle()}
                >
                  {CATEGORIES.map(c => <option key={c}>{c}</option>)}
                </select>
                <textarea
                  value={reportEvidence} onChange={(e) => setReportEvidence(e.target.value.slice(0, 300))}
                  placeholder="What happened? (max 300 chars, no personal info)"
                  rows={3}
                  style={{ ...inputStyle(), resize: "vertical", fontFamily: "inherit" }}
                />
                <div style={{ display: "flex", gap: 8 }}>
                  <button onClick={submitReport} disabled={!reportEvidence.trim()} style={{
                    flex: 1, padding: "10px 18px", borderRadius: 10,
                    background: reportEvidence.trim() ? T.red : "rgba(148,163,184,0.18)",
                    color: reportEvidence.trim() ? "#fff" : T.muted,
                    border: 0, fontWeight: 700, fontSize: 13,
                    cursor: reportEvidence.trim() ? "pointer" : "not-allowed", fontFamily: "inherit",
                  }}>Submit report</button>
                  <button onClick={() => setReporting(false)} style={{
                    padding: "10px 18px", borderRadius: 10,
                    background: "transparent", color: T.muted,
                    border: `1px solid ${T.border}`, fontSize: 13, fontWeight: 600,
                    cursor: "pointer", fontFamily: "inherit",
                  }}>Cancel</button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Educational */}
        <div style={{
          padding: 22, borderRadius: 14, marginBottom: 24,
          background: "rgba(2,6,23,0.6)", border: `1px solid ${T.border}`,
        }}>
          <h3 style={{ fontFamily: "'Vrikaan Sans', sans-serif", fontSize: 18, color: T.white, margin: "0 0 14px" }}>
            <LuCircleCheck size={18} style={{ verticalAlign: "-3px" }} color={T.green} /> Before you pay any UPI ID, always:
          </h3>
          <ol style={{ margin: 0, paddingLeft: 20, color: T.muted, fontSize: 13, lineHeight: 1.9 }}>
            <li><strong style={{ color: T.cyan }}>Type UPI ID manually</strong> — never tap "Pay this number" from a chat/SMS link.</li>
            <li><strong style={{ color: T.cyan }}>Check merchant name</strong> shown in your UPI app BEFORE tapping Pay — should match expected.</li>
            <li><strong style={{ color: T.cyan }}>₹1 test transfer first</strong> for any new merchant. Verify it lands.</li>
            <li><strong style={{ color: T.cyan }}>QR codes:</strong> long-press → "View QR contents" first. Don't blindly scan stickers.</li>
            <li><strong style={{ color: T.cyan }}>For businesses:</strong> verify GSTIN at <a href="/receipt-audit" style={{ color: T.cyan }}>vrikaan.com/receipt-audit</a>.</li>
          </ol>
        </div>

        {/* Footer */}
        <p style={{
          marginTop: 32, padding: 16, color: T.mutedDark, fontSize: 12,
          textAlign: "center", lineHeight: 1.7, borderTop: `1px solid ${T.border}`,
        }}>
          <LuLock size={13} style={{ verticalAlign: "-2px" }} /> Your reports are stored in your browser's localStorage (not shared yet).
          We're building a Firestore-backed shared database for v2 — your reports will sync once you sign in.<br/>
          🇮🇳 Built in Nashik · Free forever
        </p>
      </main>

    </ToolShell>
  );
}

function inputStyle() {
  return {
    width: "100%", padding: "11px 14px", borderRadius: 10,
    background: "rgba(2,6,23,0.6)", border: `1px solid ${T.border}`,
    color: T.white, fontSize: 14, outline: "none", fontFamily: "inherit",
    boxSizing: "border-box",
  };
}
