import { useState } from "react";
import { useUsageLimit } from "../../hooks/useUsageLimit";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import SEO from "../../components/SEO";
import { exportReport } from "../../utils/exportPDF";

const T = { bg: "#030712", card: "rgba(17,24,39,0.8)", accent: "#6366f1", cyan: "#14e3c5", green: "#22c55e", red: "#ef4444", yellow: "#fbbf24", white: "#f1f5f9", muted: "#94a3b8", border: "rgba(148,163,184,0.08)" };

function daysBetween(a, b) { return Math.floor((new Date(b) - new Date(a)) / 86400000); }
function fmtDate(d) { return d ? new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" }) : "N/A"; }

export default function WhoisLookup() {
  const { checkLimit, limitError } = useUsageLimit("whois");
  const [domain, setDomain] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  const lookup = async () => {
    if (!domain.trim()) return;
    const ok = await checkLimit();
    if (!ok) return;
    setLoading(true); setError(""); setResult(null);
    try {
      const res = await fetch("/api/tools?tool=whois", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ domain: domain.trim() }) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setResult(data);
    } catch (e) { setError(e.message); }
    setLoading(false);
  };

  const doExport = () => {
    if (!result) return;
    const age = result.creationDate ? `${daysBetween(result.creationDate, new Date())} days` : "Unknown";
    exportReport({
      title: "WHOIS Lookup Report", subtitle: result.domain,
      sections: [
        { heading: "Domain Info", items: [`Domain: ${result.domain}`, `Registrar: ${result.registrar}`, `Age: ${age}`] },
        { heading: "Dates", items: [`Created: ${fmtDate(result.creationDate)}`, `Expires: ${fmtDate(result.expiryDate)}`, `Updated: ${fmtDate(result.updatedDate)}`] },
        { heading: "Nameservers", items: result.nameservers.length ? result.nameservers : ["None found"] },
        { heading: "Status", items: result.status.length ? result.status : ["Unknown"] },
      ],
      footer: "Generated by SECUVION",
    });
  };

  const s = { input: { width: "100%", padding: "14px 16px", background: "rgba(15,23,42,0.6)", border: `1px solid ${T.border}`, borderRadius: 10, color: T.white, fontSize: 15, outline: "none", boxSizing: "border-box", fontFamily: "'Plus Jakarta Sans',sans-serif" } };

  return (
    <div style={{ minHeight: "100vh", background: T.bg, fontFamily: "'Plus Jakarta Sans',sans-serif" }}>
      <SEO title="WHOIS Lookup" description="Look up domain registration details, registrar, expiry and nameservers." path="/whois-lookup" />
      <Navbar />
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "120px 20px 60px" }}>
        <h1 style={{ fontSize: 32, fontWeight: 700, color: T.white, marginBottom: 8, fontFamily: "'Space Grotesk',sans-serif" }}>WHOIS Lookup</h1>
        <p style={{ color: T.muted, fontSize: 14, marginBottom: 28 }}>Find domain registration details, registrar, expiry date and nameservers.</p>

        <div style={{ display: "flex", gap: 10, marginBottom: 28 }}>
          <input value={domain} onChange={e => setDomain(e.target.value)} onKeyDown={e => e.key === "Enter" && lookup()} placeholder="example.com" style={{ ...s.input, flex: 1 }} />
          <button onClick={lookup} disabled={loading} style={{ padding: "14px 28px", borderRadius: 10, border: "none", background: `linear-gradient(135deg,${T.accent},${T.cyan})`, color: "#fff", fontSize: 15, fontWeight: 700, cursor: loading ? "wait" : "pointer", fontFamily: "'Space Grotesk',sans-serif", whiteSpace: "nowrap" }}>
            {loading ? "Looking up..." : "Lookup"}
          </button>
        </div>

        {(limitError || error) && <div style={{ padding: "12px 16px", background: "rgba(239,68,68,0.1)", borderRadius: 8, border: "1px solid rgba(239,68,68,0.2)", marginBottom: 20 }}><span style={{ fontSize: 13, color: T.red }}>{limitError || error}</span>{limitError && <a href="/pricing" style={{ fontSize: 13, color: T.accent, marginLeft: 8 }}>Upgrade</a>}</div>}

        {result && (
          <div style={{ background: T.card, border: `1px solid ${T.border}`, borderRadius: 16, padding: 28, backdropFilter: "blur(10px)" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
              <h2 style={{ fontSize: 22, fontWeight: 700, color: T.cyan, fontFamily: "'Space Grotesk',sans-serif", margin: 0 }}>{result.domain}</h2>
              <button onClick={doExport} style={{ padding: "8px 16px", borderRadius: 8, border: `1px solid ${T.border}`, background: "rgba(15,23,42,0.6)", color: T.muted, fontSize: 12, cursor: "pointer", fontFamily: "'Plus Jakarta Sans',sans-serif" }}>Export PDF</button>
            </div>

            {/* Info grid */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 24 }}>
              {[
                { label: "Registrar", value: result.registrar },
                { label: "Domain Age", value: result.creationDate ? `${Math.floor(daysBetween(result.creationDate, new Date()) / 365)} years, ${daysBetween(result.creationDate, new Date()) % 365} days` : "Unknown" },
                { label: "Created", value: fmtDate(result.creationDate) },
                { label: "Expires", value: fmtDate(result.expiryDate) },
                { label: "Last Updated", value: fmtDate(result.updatedDate) },
                { label: "Days Until Expiry", value: result.expiryDate ? `${daysBetween(new Date(), result.expiryDate)} days` : "N/A" },
              ].map(item => (
                <div key={item.label} style={{ padding: "14px 16px", background: "rgba(15,23,42,0.5)", borderRadius: 10, border: `1px solid ${T.border}` }}>
                  <div style={{ fontSize: 11, color: T.muted, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 }}>{item.label}</div>
                  <div style={{ fontSize: 14, fontWeight: 600, color: T.white }}>{item.value}</div>
                </div>
              ))}
            </div>

            {/* Nameservers */}
            {result.nameservers.length > 0 && (
              <div style={{ marginBottom: 20 }}>
                <h3 style={{ fontSize: 14, fontWeight: 600, color: T.white, marginBottom: 10 }}>Nameservers</h3>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                  {result.nameservers.map(ns => (
                    <span key={ns} style={{ padding: "6px 12px", borderRadius: 6, background: "rgba(99,102,241,0.1)", border: "1px solid rgba(99,102,241,0.2)", fontSize: 13, color: T.accent, fontFamily: "'JetBrains Mono',monospace" }}>{ns}</span>
                  ))}
                </div>
              </div>
            )}

            {/* Status */}
            {result.status.length > 0 && (
              <div>
                <h3 style={{ fontSize: 14, fontWeight: 600, color: T.white, marginBottom: 10 }}>Status Codes</h3>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                  {result.status.map(st => (
                    <span key={st} style={{ padding: "5px 10px", borderRadius: 6, background: st.includes("ok") || st.includes("active") ? "rgba(34,197,94,0.1)" : "rgba(148,163,184,0.1)", border: `1px solid ${st.includes("ok") || st.includes("active") ? "rgba(34,197,94,0.2)" : T.border}`, fontSize: 12, color: st.includes("ok") || st.includes("active") ? T.green : T.muted }}>{st}</span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
}
