/**
 * PDF Report Export Utility
 *
 * Generates a professional PDF report from scan results using the
 * browser's built-in print dialog. No external libraries required.
 *
 * @example
 *   import { exportReport } from '../utils/exportPDF';
 *
 *   exportReport({
 *     title: 'Vulnerability Scan Report',
 *     subtitle: 'Target: example.com',
 *     sections: [
 *       {
 *         heading: 'Summary',
 *         items: [
 *           { label: 'Risk Level', value: 'High', color: '#ef4444' },
 *           { label: 'Issues Found', value: '12' },
 *         ],
 *       },
 *     ],
 *     footer: 'Custom footer text (optional)',
 *   });
 */

const DEFAULT_FOOTER =
  'Generated by VRIKAAN \u2014 AI-Powered Cyber Defense Platform \u2022 vrikaan.com';

function escapeHtml(str) {
  if (typeof str !== 'string') return String(str ?? '');
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildSectionHtml(section) {
  const items = (section.items || [])
    .map(
      (item) => `
        <div class="item">
          <span class="item-label">${escapeHtml(item.label)}</span>
          <span class="item-value"${item.color ? ` style="color:${escapeHtml(item.color)}"` : ''}>${escapeHtml(item.value)}</span>
        </div>`
    )
    .join('');

  return `
    <div class="section">
      <div class="section-heading">${escapeHtml(section.heading)}</div>
      ${items}
    </div>`;
}

function buildDocument({ title, subtitle, sections, footer }) {
  const timestamp = new Date().toLocaleString();
  const sectionsHtml = (sections || []).map(buildSectionHtml).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <title>${escapeHtml(title)} - VRIKAAN Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px;
      color: #1e293b;
    }

    /* Header */
    .header {
      border-bottom: 3px solid #6366f1;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .logo {
      font-size: 24px;
      font-weight: 800;
      color: #6366f1;
      letter-spacing: 2px;
    }
    .title {
      font-size: 20px;
      font-weight: 700;
      margin-top: 8px;
    }
    .subtitle {
      font-size: 13px;
      color: #64748b;
      margin-top: 4px;
    }
    .timestamp {
      font-size: 11px;
      color: #94a3b8;
      margin-top: 8px;
    }

    /* Sections */
    .section {
      margin-bottom: 24px;
    }
    .section-heading {
      font-size: 15px;
      font-weight: 700;
      color: #6366f1;
      margin-bottom: 12px;
      border-left: 3px solid #6366f1;
      padding-left: 10px;
    }

    /* Items */
    .item {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #e2e8f0;
      font-size: 13px;
    }
    .item-label { color: #64748b; }
    .item-value { font-weight: 600; }

    /* Footer */
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
      font-size: 11px;
      color: #94a3b8;
      text-align: center;
    }

    @media print {
      body { padding: 20px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">VRIKAAN</div>
    <div class="title">${escapeHtml(title)}</div>
    ${subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : ''}
    <div class="timestamp">Generated: ${timestamp}</div>
  </div>

  ${sectionsHtml}

  <div class="footer">${escapeHtml(footer || DEFAULT_FOOTER)}</div>
</body>
</html>`;
}

/**
 * Opens a new browser window with a styled report and triggers the
 * print dialog so the user can save as PDF.
 *
 * @param {Object}   options
 * @param {string}   options.title     - Main report title.
 * @param {string}   [options.subtitle] - Optional subtitle (e.g. target URL).
 * @param {Array}    options.sections  - Array of { heading, items }.
 *   Each item is { label, value, color? }.
 * @param {string}   [options.footer]  - Custom footer text.
 */
export function exportReport({ title, subtitle, sections, footer } = {}) {
  if (!title) {
    console.error('[exportReport] A title is required.');
    return;
  }
  if (!sections || sections.length === 0) {
    console.error('[exportReport] At least one section is required.');
    return;
  }

  const html = buildDocument({ title, subtitle, sections, footer });

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error(
      '[exportReport] Unable to open print window. Check your pop-up blocker settings.'
    );
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.print();
}
